### ISSUE TITLE
Database is not cleaning up after missing 3 heartbeats

### ISSUE THREAD

**Issue by GportDev** [tntech-ngin/ndn-hydra#26] opened 2024-05-30 14:38 UTC

**Comment by sankalpatimilsina12** [comment] 2024-06-01 12:47
I am not sure if we want to clean the database upon every hydra initiation. Since the database is persistent, the hydra picks up whatever was previously there.

Please correct this if not so: @susmit85 @GportDev

**Comment by sankalpatimilsina12** [comment] 2024-06-01 12:53
@GportDev Could you please provide a sequence to steps to reproduce the issue? Thanks.

**Comment by GportDev** [comment] 2024-06-03 13:37
If we did not listen from the node in 3 heartbeat then we should clean the database of this particular node

**Comment by sankalpatimilsina12** [comment] 2024-06-03 17:58
I've verified that the node expiration is indeed executed, and the node is marked as expired in the database, the heartbeats seem like they are working properly. 

@susmit85 @GportDev

**Comment by tntech-ngin** [comment] 2024-06-12 13:47
When the nodes do not hear from another node for 3 heartbeats, it marks that node expired. Expired nodes are not currently deleted from the database.

**Closed by tntech-ngin** 2024-06-12 13:47 UTC
